---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marlonfa/public_html/sequence_client
    - /bin/cp clientMain.js $DEPLOYPATH
    - export DEPLOYPATH=/home/marlonfa/public_html/sequence_client/public/css
    - /bin/cp index.css $DEPLOYPATH
    - /bin/cp gamePage.css $DEPLOYPATH
    - /bin/cp leaderboard.css $DEPLOYPATH
    # - /bin/cp -r /home/marlonfa/public_html/sequence_client/public/css $DEPLOYPATH
    # - /bin/cp -r /home/marlonfa/public_html/sequence_client/public/script $DEPLOYPATH
    - export DEPLOYPATH=/home/marlonfa/public_html/sequence_client/public/script
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp gamePage.js $DEPLOYPATH
    - /bin/cp leaderboard.js $DEPLOYPATH
    - export DEPLOYPATH=/home/marlonfa/public_html/sequence_client/views 
    - /bin/cp -r /home/marlonfa/public_html/sequence_client/views/pages $DEPLOYPATH